// <auto-generated />
namespace ZumraApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CREATE_DATABASE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREATE_DATABASE));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191513378_CREATE_DATABASE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
